apiVersion: v1
kind: Service
metadata:
  name: nextwork-web-service
spec:
  selector:
    app: nextwork-web
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080       # Port exposed inside cluster
      targetPort: 8080 # Container port
      nodePort: 30080  # Port exposed on your node (Minikube host)
