apiVersion: v1
kind: pod
metadata:
  name: postgress-pod
  labels:
    name: postgress-pod
    app: demo-voting-app
spec:
  containers:
     - name: postgress
       image: postgress
       ports:
         - containerPort: 5432 #default port for postgress
       env:
         - name: POSTGRESS_USER
           value: "postgress"
         - name: POSTGRESS_PASSWORD
           value: "postgress"
